"""Added relationships

Revision ID: 7e74da651b1e
Revises: b2dc8752ebfb
Create Date: 2020-01-28 22:04:17.726695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e74da651b1e'
down_revision = 'b2dc8752ebfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Questionnaire',
    sa.Column('question_1', sa.String(), nullable=True),
    sa.Column('question_2', sa.String(), nullable=True),
    sa.Column('question_3', sa.String(), nullable=True),
    sa.Column('question_4', sa.String(), nullable=True),
    sa.Column('question_5', sa.String(), nullable=True),
    sa.Column('question_6', sa.String(), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('questionnaire_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Questionnaire')
    # ### end Alembic commands ###
